### ISSUE TITLE
如何处理鼠标事件透传？

### ISSUE THREAD

**Issue by jwang0512** [SOUI2/soui.backup#22]
我想改造STabCtrl，让Tab头一行没显示Tab的地方透传鼠标事件给后面的控件，请教该如何处理？

改造想法：
我把STabCtrl覆盖在了caption控件上，这样caption上的最小化、最大化、关闭按钮都被STabCtrl遮盖而无法响应鼠标事件，但我的这个STabCtrl实际上只有3个Tab，视觉上并未盖住caption的最小化、最大化、关闭按钮。因此想改造STabCtrl，让STabCtrl::HitTest()为-1时不处理鼠标事件，并将鼠标事件继续传递给后面的控件（caption）

**Comment by setoutsoft** [comment]
这种情况最好就是隐藏tab头（设置tabHeight=0)，用一组radioButton来代替切换tab.

**Comment by jwang0512** [comment]
这是一个办法，但感觉不具有通用性。同时一个整体组件被拆成了几个部分。
如果是想做透传鼠标事件的话，改如何处理，我大概看了下，似乎没有看到传递事件的相关代码。

**Comment by setoutsoft** [comment]
你可以自己在hitTest的时候告诉host光标不在tab窗口里。

**Comment by jwang0512** [comment]
@setoutsoft 感谢，应该没啥大问题了，如你所说覆盖SwndFromPoint处理应该可行。
